Changes introduced by gcc-5363.tar.gz (2006-06-27, mac-os-x-1048x86)
Source: http://opensource.apple.com/tarballs/gcc/gcc-5363.tar.gz
SHA-1: 0d9712d2b092c64c8b42757d6e135a2ef6f046e0
OS X Release: mac-os-x-1048x86 (source release #039)
File Modification Timestamp (Oldest): 1998-05-15 23:15:01
File Modification Timestamp (Newest): 2006-06-27 07:29:34

diff --git a/src/gcc/gcc/configure b/src/gcc/gcc/configure
--- a/src/gcc/gcc/configure
+++ b/src/gcc/gcc/configure
@@ -11288,6 +11288,7 @@ _ACEOF
 # We will need to find libiberty.h and ansidecl.h
 saved_CFLAGS="$CFLAGS"
 CFLAGS="$CFLAGS -I${srcdir} -I${srcdir}/../include"
+# APPLE LOCAL begin mainline llvm
 
 
 
@@ -11325,7 +11326,8 @@ CFLAGS="$CFLAGS -I${srcdir} -I${srcdir}/../include"
 
 
 
-for ac_func in getenv atol sbrk abort atof getcwd getwd strsignal \
+
+for ac_func in getenv atol asprintf sbrk abort atof getcwd getwd strsignal \
 	strverscmp \
 	strstr errno snprintf vasprintf malloc realloc calloc free \
 	basename getopt clock getpagesize clearerr_unlocked feof_unlocked   ferror_unlocked fflush_unlocked fgetc_unlocked fgets_unlocked   fileno_unlocked fprintf_unlocked fputc_unlocked fputs_unlocked   fread_unlocked fwrite_unlocked getchar_unlocked getc_unlocked   putchar_unlocked putc_unlocked
@@ -11406,6 +11408,7 @@ fi
 
 done
 
+# APPLE LOCAL end mainline llvm
 
 
 
@@ -12313,7 +12316,7 @@ fi
   if test x$use_cxa_atexit = xyes; then
 
 cat >>confdefs.h <<\_ACEOF
-#define DEFAULT_USE_CXA_ATEXIT 1
+#define DEFAULT_USE_CXA_ATEXIT 2
 _ACEOF
 
   fi
@@ -13307,6 +13310,45 @@ cat >>confdefs.h <<\_ACEOF
 _ACEOF
 
 fi
+
+# APPLE LOCAL begin x86_64 literal16
+echo "$as_me:$LINENO: checking assembler for .literal16" >&5
+echo $ECHO_N "checking assembler for .literal16... $ECHO_C" >&6
+if test "${gcc_cv_as_literal16+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  gcc_cv_as_literal16=no
+    if test $in_tree_gas = yes; then
+    if test $gcc_cv_gas_vers -ge `expr \( \( 2 \* 1000 \) + 8 \) \* 1000 + 0`
+  then gcc_cv_as_literal16=yes
+fi
+  elif test x$gcc_cv_as != x; then
+    echo '.literal16' > conftest.s
+    if { ac_try='$gcc_cv_as  -o conftest.o conftest.s >&5'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }
+    then
+	gcc_cv_as_literal16=yes
+    else
+      echo "configure: failed program was" >&5
+      cat conftest.s >&5
+    fi
+    rm -f conftest.o conftest.s
+  fi
+fi
+echo "$as_me:$LINENO: result: $gcc_cv_as_literal16" >&5
+echo "${ECHO_T}$gcc_cv_as_literal16" >&6
+if test $gcc_cv_as_literal16 = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_GAS_LITERAL16 1
+_ACEOF
+
+fi
+# APPLE LOCAL end x86_64 literal16
 
 echo "$as_me:$LINENO: checking assembler for working .subsection -1" >&5
 echo $ECHO_N "checking assembler for working .subsection -1... $ECHO_C" >&6
